openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Sample Website'
security:
  - BasicAuth : []
servers:
  - url: 'http://localhost:3000'
  - url: 'https://e0e24e57-d428-461c-8d2b-9be76e52fb76.mock.pstmn.io'
  - url: 'https://xewf1gd1a9.execute-api.ap-southeast-2.amazonaws.com/latest'
paths:
  /:
    get:
      summary: 'Sample endpoint: Returns the home page of the website'
      operationId: homepage
      security:
        - BasicAuth : []
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/homepage'

components:
  schemas:
    homepage:
      type: string
      example: '<html><body><h1>This is my Updated Home Page</h1></body></html>'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic